# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb49f205b98dbbf3891adcad42518c76544868f77b17627a56b4f1a66ede4f7918432f71c5771060be7a7e4d4509b24a5a90a4b1915df8951269087b8bc8eafa

test:
  secret_key_base: 48f35e4b3b7f12d4e81656a6a2ea9bef13f5d638f3b32d7937f22aff8a0982c5691d58eae4fe2a36b48bf92ca4a77a8336cd9a3d5c2c47edecfed24b8df43a1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
